# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, verbose_name='나이'),
        ),
    ]
